### ISSUE TITLE
Prepping Thrombin to reproduce TIES paper

### ISSUE THREAD

**Issue by AlexW12344** [UCL-CCS/TIES#326]
Hiya,

If I want to prep Thrombin to reproduce the TIES paper what is the best way to include the disulfide bridges? The standard TIES protein prep pipeline with tleap does not add these. How was this protein prepped for the paper? https://pubs.acs.org/doi/abs/10.1021/acs.jctc.0c01179

Cheers,
Alex

**Comment by apbhati1** [comment]
Hey Alex,

In order for tleap to add disulphide bridges, the best way could be to (a) define all of them (SG-SG bonds) in the input PDB after the coordinates (see example provided below), and (b) rename all CYS residues involved to CYX. After this, tleap should automatically add disuphide bridges.

"ATOM   3059  O   ASN A 446       5.544  47.384  99.520  1.00 46.31           O
ATOM   3060  OXT ASN A 446       6.037  45.354  99.711  1.00  0.00           O
TER    3061      ASN A 446
CONECT 1251 2851
CONECT 1737 3033
CONECT 2142 2546
CONECT 2546 2142
CONECT 2851 1251
CONECT 3033 1737
END"

Hope this helps!

Cheers,
Agastya

**Comment by adw62** [comment]
Hey Agastya,

I put the CYX as they describe here https://ambermd.org/tutorials/basic/tutorial7/index.php but did not see the bridges at the end. They also discuss using the bond command in LEaP to define which CYX are bound to each other which would need modification to the default tleap script in TIES?

I will try again and leave the connect information in the PDB. I hope with CYX and the connect tleap will add the bridges automatically.

Cheers,
Alex

**Comment by apbhati1** [comment]
hey Alex,

That's right. Using the bond command would require modification to the code base, this is why I prefer the approach I suggested. Please give it a go and let me know if you face issues with that.

Cheers,
Agastya

**Comment by AlexW12344** [comment]
Okay nice thanks for the advice this works well to build the bridges :)
