### ISSUE TITLE
use_element_in_superimposition

### ISSUE THREAD

**Issue by AlexW12344** [UCL-CCS/TIES#329]
Hiya,

I noticed that `use_element_in_superimposition=True` raises the warning 'Warning. Ignoring the specific atom types during superimposition. The results should not be used in production simulations.' but the description does not sound so bad https://github.com/UCL-CCS/TIES/blob/master/ties/pair.py#L90C9-L91C85 suggesting the atoms types are still considered in the final solution?

Should `use_element_in_superimposition=True` really be avoided for production. How might this effect the results?

Cheers,
Alex

**Comment by AlexW12344** [comment]
Okay phew because I was using `use_element_in_superimposition=True` everywhere then saw this warning haha

**Comment by bieniekmateusz** [comment]
Sorry! I promise to clean it up a bit (next year it seems!)
